name: Deploy to Render

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-to-render:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm ci
        npm run install:apps
        
    - name: Build all modules
      run: |
        npm run build:shell
        npm run build:home
        npm run build:products
        npm run build:profile
        
    - name: Deploy to Render
      uses: johnbeynon/render-deploy-action@v0.0.9
      with:
        service-id: ${{ secrets.RENDER_SERVICE_ID }}
        api-key: ${{ secrets.RENDER_API_KEY }}
        wait-for-success: true

